cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      logged_in: false
      name: John Smith
      password: $2b$12$fDfoX4EyySfs5M8HT5sqXOZfXQaDaxvJ4AA/emq7FT49aJcYkmSLW
    rbriggs:
      email: rbriggs@gmail.com
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$kCsjylhSmZpeoMcYGakn8OOKm5/6Ol.jVOK7v/s7L8W91yd0R70z2
preauthorized:
  emails:
  - melsby@gmail.com
